# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 71b007627d62961068b292a8ea8edeb5ff3f5beee8068d865b04c86ebb66514488f5e968925b3551a3747a5e34b8df9006aab6dc6118507f4041bd9ca5a377be

test:
  secret_key_base: 4ee49e4fc0e7f46bf57542a54a4222c67f524efe6f6a90d52914675a4a57d3034af04938b2012d18d9a6088eb8339c0377f36511d38c56c0ba11505588da08c8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
